# Generated by Django 5.2.8 on 2026-01-04 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('instagram_link', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_hours', models.CharField(default='09:00-18:00', max_length=50)),
                ('tuesday_hours', models.CharField(default='09:00-18:00', max_length=50)),
                ('wednesday_hours', models.CharField(default='09:00-18:00', max_length=50)),
                ('thursday_hours', models.CharField(default='09:00-18:00', max_length=50)),
                ('friday_hours', models.CharField(default='09:00-18:00', max_length=50)),
                ('saturday_hours', models.CharField(default='09:00-18:00', max_length=50)),
                ('sunday_hours', models.CharField(default='CERRADO', max_length=50)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='businesses.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Negocio')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('city', models.CharField(default='Bogotá', max_length=100, verbose_name='Ciudad')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección Física')),
                ('whatsapp_number', models.CharField(blank=True, max_length=50)),
                ('instagram_link', models.URLField(blank=True)),
                ('maps_link', models.URLField(blank=True)),
                ('deposit_percentage', models.IntegerField(default=50)),
                ('opening_time', models.TimeField(default='08:00')),
                ('closing_time', models.TimeField(default='20:00')),
                ('work_monday', models.BooleanField(default=True)),
                ('work_tuesday', models.BooleanField(default=True)),
                ('work_wednesday', models.BooleanField(default=True)),
                ('work_thursday', models.BooleanField(default=True)),
                ('work_friday', models.BooleanField(default=True)),
                ('work_saturday', models.BooleanField(default=True)),
                ('work_sunday', models.BooleanField(default=False)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salon', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='businesses.salon'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('duration', models.IntegerField(default=30)),
                ('buffer_time', models.IntegerField(default=10)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='businesses.salon')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('deposit_amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING_PAYMENT', 'Pendiente'), ('VERIFIED', 'Confirmada'), ('COMPLETED', 'Completada'), ('CANCELLED', 'Cancelada')], default='PENDING_PAYMENT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.employee')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='businesses.salon')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.service')),
            ],
        ),
    ]
