# Generated by Django 5.2.8 on 2026-01-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='deposit_percentage',
            field=models.PositiveIntegerField(default=30, verbose_name='Porcentaje de Abono'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='description',
            field=models.TextField(blank=True, help_text='Para el buscador semántico', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='google_maps_url',
            field=models.URLField(blank=True, verbose_name='Link Google Maps'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='is_open_manually',
            field=models.BooleanField(default=True, verbose_name='Abierto Manualmente'),
        ),
        migrations.AlterField(
            model_name='service',
            name='buffer_minutes',
            field=models.PositiveIntegerField(default=10, verbose_name='Tiempo de Limpieza (min)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(verbose_name='Descripción / Palabras Clave'),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration_minutes',
            field=models.PositiveIntegerField(verbose_name='Duración (min)'),
        ),
    ]
