# Generated by Django 5.2.8 on 2026-01-04 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Pendiente'), ('VERIFIED', 'Confirmada'), ('COMPLETED', 'Completada'), ('CANCELLED', 'Cancelada')], default='PENDING_PAYMENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='instagram_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='salon',
            name='closing_time',
            field=models.TimeField(default='20:00'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='deposit_percentage',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='salon',
            name='instagram_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='salon',
            name='maps_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='salon',
            name='opening_time',
            field=models.TimeField(default='08:00'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='salon',
            name='work_friday',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='salon',
            name='work_monday',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='salon',
            name='work_saturday',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='salon',
            name='work_sunday',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='salon',
            name='work_thursday',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='salon',
            name='work_tuesday',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='salon',
            name='work_wednesday',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='buffer_time',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.IntegerField(default=30),
        ),
    ]
