# Generated by Django 5.2.8 on 2026-01-03 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='instagram',
            field=models.CharField(blank=True, default='', help_text='Usuario sin @', max_length=100, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='salon',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='salon',
            name='whatsapp',
            field=models.CharField(blank=True, default='', help_text='Ej: +57 300 123 4567', max_length=50, verbose_name='WhatsApp'),
        ),
    ]
