# Generated by Django 5.2.8 on 2026-01-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_alter_businessprofile_deposit_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='is_active_subscription',
            field=models.BooleanField(default=False, verbose_name='Suscripción Activa'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='subscription_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Corte'),
        ),
    ]
