# Generated by Django 5.2.8 on 2026-01-04 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_alter_booking_status_alter_employee_instagram_link_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='customer_phone',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='service',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='closing_time',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='deposit_percentage',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='maps_link',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='opening_time',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='whatsapp_number',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='work_friday',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='work_monday',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='work_saturday',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='work_sunday',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='work_thursday',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='work_tuesday',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='work_wednesday',
        ),
        migrations.RemoveField(
            model_name='service',
            name='buffer_time',
        ),
        migrations.RemoveField(
            model_name='service',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='service',
            name='is_active',
        ),
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='services',
            field=models.ManyToManyField(to='businesses.service'),
        ),
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.TimeField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default=1, max_length=100, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default=1, max_length=100, verbose_name='Apellido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salon',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo del Negocio'),
        ),
        migrations.AddField(
            model_name='salon',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='salon',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='salon',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=50, verbose_name='WhatsApp'),
        ),
        migrations.AddField(
            model_name='service',
            name='duration_minutes',
            field=models.IntegerField(default=30, verbose_name='Duración (min)'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='businesses.employee'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente de Abono'), ('confirmed', 'Cita Verificada'), ('cancelled', 'Cancelada')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='employeeschedule',
            name='friday_hours',
            field=models.CharField(blank=True, default='09:00-18:00', max_length=50),
        ),
        migrations.AlterField(
            model_name='employeeschedule',
            name='monday_hours',
            field=models.CharField(blank=True, default='09:00-18:00', max_length=50),
        ),
        migrations.AlterField(
            model_name='employeeschedule',
            name='saturday_hours',
            field=models.CharField(blank=True, default='09:00-18:00', max_length=50),
        ),
        migrations.AlterField(
            model_name='employeeschedule',
            name='sunday_hours',
            field=models.CharField(blank=True, default='CERRADO', max_length=50),
        ),
        migrations.AlterField(
            model_name='employeeschedule',
            name='thursday_hours',
            field=models.CharField(blank=True, default='09:00-18:00', max_length=50),
        ),
        migrations.AlterField(
            model_name='employeeschedule',
            name='tuesday_hours',
            field=models.CharField(blank=True, default='09:00-18:00', max_length=50),
        ),
        migrations.AlterField(
            model_name='employeeschedule',
            name='wednesday_hours',
            field=models.CharField(blank=True, default='09:00-18:00', max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre del Servicio'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Precio'),
        ),
        migrations.CreateModel(
            name='SalonSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_open', models.BooleanField(default=True, verbose_name='Lunes')),
                ('tuesday_open', models.BooleanField(default=True, verbose_name='Martes')),
                ('wednesday_open', models.BooleanField(default=True, verbose_name='Miércoles')),
                ('thursday_open', models.BooleanField(default=True, verbose_name='Jueves')),
                ('friday_open', models.BooleanField(default=True, verbose_name='Viernes')),
                ('saturday_open', models.BooleanField(default=True, verbose_name='Sábado')),
                ('sunday_open', models.BooleanField(default=False, verbose_name='Domingo')),
                ('salon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='businesses.salon')),
            ],
        ),
    ]
