# Generated by Django 4.2.27 on 2025-12-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Dirección Física'),
        ),
        migrations.AddField(
            model_name='salon',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Celular del Negocio'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='city',
            field=models.CharField(default='Tunja', max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre del Negocio'),
        ),
    ]
