# Generated by Django 5.2.8 on 2026-01-09 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeschedule',
            name='active_days',
            field=models.CharField(default='0,1,2,3,4,5', max_length=20),
        ),
        migrations.AddField(
            model_name='employeeschedule',
            name='lunch_end',
            field=models.TimeField(default='14:00'),
        ),
        migrations.AddField(
            model_name='employeeschedule',
            name='lunch_start',
            field=models.TimeField(default='13:00'),
        ),
        migrations.AddField(
            model_name='employeeschedule',
            name='work_end',
            field=models.TimeField(default='18:00'),
        ),
        migrations.AddField(
            model_name='employeeschedule',
            name='work_start',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='deposit_percentage',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='buffer_time',
            field=models.IntegerField(default=15, help_text='Limpieza (min)'),
        ),
    ]
