# Generated by Django 5.2.8 on 2026-01-03 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_salon_instagram_salon_phone_salon_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalonSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_open', models.BooleanField(default=True, verbose_name='Lunes')),
                ('tuesday_open', models.BooleanField(default=True, verbose_name='Martes')),
                ('wednesday_open', models.BooleanField(default=True, verbose_name='Miércoles')),
                ('thursday_open', models.BooleanField(default=True, verbose_name='Jueves')),
                ('friday_open', models.BooleanField(default=True, verbose_name='Viernes')),
                ('saturday_open', models.BooleanField(default=True, verbose_name='Sábado')),
                ('sunday_open', models.BooleanField(default=False, verbose_name='Domingo')),
                ('salon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='businesses.salon')),
            ],
        ),
    ]
