# Generated by Django 5.2.8 on 2026-01-03 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_salonschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='duration_minutes',
            field=models.IntegerField(default=30, verbose_name='Duración (min)'),
        ),
    ]
