# Generated by Django 5.2.8 on 2026-01-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_employeeschedule_active_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='active_days',
            field=models.CharField(default='0,1,2,3,4,5', max_length=20),
        ),
    ]
