# Generated by Django 4.2.27 on 2025-12-15 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_salon_address_salon_phone_alter_salon_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bold_api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='API Key (Bold)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='bold_signing_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Signing Key (Bold)'),
        ),
        migrations.CreateModel(
            name='EmployeeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('from_hour', models.TimeField()),
                ('to_hour', models.TimeField()),
                ('is_closed', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='businesses.employee')),
            ],
            options={
                'ordering': ('weekday', 'from_hour'),
                'unique_together': {('employee', 'weekday')},
            },
        ),
    ]
