# Generated by Django 5.2.8 on 2025-12-23 17:04

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_salon_phone_employeeschedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeeschedule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='salon',
            name='bold_api_key',
            field=models.CharField(blank=True, help_text='Llave de Identidad', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='salon',
            name='bold_secret_key',
            field=models.CharField(blank=True, help_text='Llave Secreta', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='salon',
            name='closing_time',
            field=models.TimeField(default=datetime.time(20, 0), verbose_name='Cierra a las'),
        ),
        migrations.AddField(
            model_name='salon',
            name='opening_time',
            field=models.TimeField(default=datetime.time(8, 0), verbose_name='Abre a las'),
        ),
        migrations.AddField(
            model_name='salon',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_salons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salon',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='ID del chat o grupo', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salon',
            name='telegram_token',
            field=models.CharField(blank=True, help_text='Token del BotFather', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salon',
            name='phone',
            field=models.CharField(default='573000000000', max_length=20, verbose_name='WhatsApp'),
        ),
    ]
