# Generated by Django 4.2.27 on 2025-12-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_employee_bold_api_key_employee_bold_signing_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='facebook',
            field=models.URLField(blank=True, verbose_name='Link Facebook'),
        ),
        migrations.AddField(
            model_name='salon',
            name='instagram',
            field=models.URLField(blank=True, verbose_name='Link Instagram'),
        ),
        migrations.AddField(
            model_name='salon',
            name='latitude',
            field=models.FloatField(default=0.0, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='salon',
            name='longitude',
            field=models.FloatField(default=0.0, verbose_name='Longitud'),
        ),
        migrations.AddField(
            model_name='salon',
            name='tiktok',
            field=models.URLField(blank=True, verbose_name='Link TikTok'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Celular'),
        ),
    ]
