# Generated by Django 6.0.1 on 2026-01-15 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_salon_active_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Número de Cuenta'),
        ),
        migrations.AddField(
            model_name='salon',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre del Banco'),
        ),
    ]
