# Generated by Django 6.0.1 on 2026-01-16 03:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_salon_account_number_salon_bank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeschedule',
            name='lunch_end',
            field=models.TimeField(blank=True, default=datetime.time(14, 0), null=True),
        ),
        migrations.AlterField(
            model_name='employeeschedule',
            name='lunch_start',
            field=models.TimeField(blank=True, default=datetime.time(13, 0), null=True),
        ),
        migrations.AlterField(
            model_name='employeeschedule',
            name='work_end',
            field=models.TimeField(blank=True, default=datetime.time(18, 0), null=True),
        ),
        migrations.AlterField(
            model_name='employeeschedule',
            name='work_start',
            field=models.TimeField(blank=True, default=datetime.time(9, 0), null=True),
        ),
    ]
