# Generated by Django 5.2.8 on 2026-01-03 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_remove_openinghours_salon_remove_schedule_salon_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EmployeeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_hours', models.CharField(blank=True, default='09:00-18:00', max_length=50)),
                ('tuesday_hours', models.CharField(blank=True, default='09:00-18:00', max_length=50)),
                ('wednesday_hours', models.CharField(blank=True, default='09:00-18:00', max_length=50)),
                ('thursday_hours', models.CharField(blank=True, default='09:00-18:00', max_length=50)),
                ('friday_hours', models.CharField(blank=True, default='09:00-18:00', max_length=50)),
                ('saturday_hours', models.CharField(blank=True, default='09:00-18:00', max_length=50)),
                ('sunday_hours', models.CharField(blank=True, default='CERRADO', max_length=50)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='businesses.employee')),
            ],
        ),
    ]
