# Generated by Django 4.2.27 on 2025-12-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_salon_facebook_salon_instagram_salon_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='telegram_bot_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram Bot Token'),
        ),
        migrations.AddField(
            model_name='employee',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram Chat ID'),
        ),
    ]
