# Generated by Django 5.2.8 on 2025-12-25 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0006_booking_amount_paid_booking_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='Enlace de Instagram'),
        ),
        migrations.AddField(
            model_name='salon',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de WhatsApp'),
        ),
    ]
