# Generated by Django 5.2.8 on 2025-12-19 15:48

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0006_employee_telegram_bot_token_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeschedule',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='employeeschedule',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='employee',
            name='specialties',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='invite_token',
        ),
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(default='Empleado', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='salon',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='salons/banners/'),
        ),
        migrations.AddField(
            model_name='salon',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='salon',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='salons/logos/'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='businesses.employee'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(default='confirmed', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bold_api_key',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='bold_signing_key',
            field=models.CharField(blank=True, default='00000', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='lunch_end',
            field=models.TimeField(default=datetime.time(13, 0)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='lunch_start',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='telegram_bot_token',
            field=models.CharField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='telegram_chat_id',
            field=models.CharField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeeschedule',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='businesses.employee'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='bold_api_key',
            field=models.CharField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salon',
            name='bold_signing_key',
            field=models.CharField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salon',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='salon',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='salon',
            name='latitude',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='salon',
            name='longitude',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='salon',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre del Negocio'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='telegram_bot_token',
            field=models.CharField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salon',
            name='telegram_chat_id',
            field=models.CharField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salon',
            name='tiktok',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
