# Generated by Django 5.2.8 on 2026-01-19 23:36

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0008_alter_employeeschedule_id_alter_salon_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeschedule',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='EmployeeWeeklySchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('week_number', models.IntegerField()),
                ('work_start', models.TimeField(default=datetime.time(9, 0))),
                ('work_end', models.TimeField(default=datetime.time(18, 0))),
                ('lunch_start', models.TimeField(default=datetime.time(13, 0))),
                ('lunch_end', models.TimeField(default=datetime.time(14, 0))),
                ('active_days', models.CharField(default='0,1,2,3,4,5', max_length=100)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['year', 'week_number'],
                'unique_together': {('employee', 'year', 'week_number')},
            },
        ),
    ]
