# Generated by Django 5.2.8 on 2026-01-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0010_alter_employeeschedule_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeschedule',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employeeweeklyschedule',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
