# Generated by Django 6.0.1 on 2026-01-26 02:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0012_alter_employeeschedule_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='closing_time',
            field=models.TimeField(blank=True, default=datetime.time(18, 0), null=True),
        ),
        migrations.AlterField(
            model_name='salon',
            name='opening_time',
            field=models.TimeField(blank=True, default=datetime.time(9, 0), null=True),
        ),
    ]
