# Generated by Django 6.0.1 on 2026-01-26 02:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0013_alter_salon_closing_time_alter_salon_opening_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='closing_time',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AlterField(
            model_name='salon',
            name='opening_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
