# Generated by Django 6.0 on 2025-12-29 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0009_booking_created_at'),
        ('core_saas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='businesses.salon', verbose_name='Salón Asignado'),
        ),
    ]
