# Generated by Django 5.2.8 on 2026-01-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='PASO Ecosistema', max_length=100, verbose_name='Nombre del Sitio')),
                ('support_whatsapp', models.CharField(help_text='Donde los dueños envían los comprobantes', max_length=20, verbose_name='WhatsApp de Soporte (Tú)')),
                ('telegram_bot_token', models.CharField(blank=True, max_length=200, verbose_name='Token del Bot de Telegram')),
                ('telegram_chat_id', models.CharField(blank=True, max_length=100, verbose_name='Tu Chat ID de Telegram')),
                ('instagram_link', models.URLField(blank=True, verbose_name='Instagram PASO')),
                ('facebook_link', models.URLField(blank=True, verbose_name='Facebook PASO')),
                ('linkedin_link', models.URLField(blank=True, verbose_name='LinkedIn PASO')),
            ],
            options={
                'verbose_name': '⚙️ Configuración del Ecosistema',
                'verbose_name_plural': '⚙️ Configuración del Ecosistema',
            },
        ),
    ]
