# Generated by Django 5.2.8 on 2026-01-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_platformsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active_account',
            field=models.BooleanField(default=True, verbose_name='Cuenta Activa'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='support_whatsapp',
            field=models.CharField(help_text='Número donde los dueños envían comprobantes', max_length=20, verbose_name='WhatsApp de Soporte'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='telegram_bot_token',
            field=models.CharField(blank=True, max_length=200, verbose_name='Token Bot Telegram'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Chat ID Telegram'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, help_text='Ciudad seleccionada del dropdown de 1101 municipios', max_length=100, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='user',
            name='instagram_link',
            field=models.URLField(blank=True, null=True, verbose_name='Perfil de Instagram'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified_payment',
            field=models.BooleanField(default=False, help_text='Si es Falso pasadas 24h, el sistema lo eliminará.', verbose_name='Pago Mensualidad Verificado'),
        ),
    ]
