# Generated by Django 5.2.8 on 2026-01-05 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_alter_businessprofile_deposit_percentage_and_more'),
        ('core', '0003_user_is_active_account_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platformsettings',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='workplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='businesses.businessprofile'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='facebook_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='instagram_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='linkedin_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='support_whatsapp',
            field=models.CharField(max_length=20, verbose_name='WhatsApp de Soporte'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='telegram_bot_token',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified_payment',
            field=models.BooleanField(default=False, verbose_name='Pago Mensualidad Verificado'),
        ),
    ]
