# Generated by Django 5.2.8 on 2026-01-04 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_saas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformsettings',
            name='instagram_link',
            field=models.URLField(blank=True, help_text='Link completo de Instagram'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Número WhatsApp del soporte', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Cliente'), ('OWNER', 'Dueño de Negocio'), ('EMPLOYEE', 'Empleado')], default='CLIENT', max_length=20),
        ),
    ]
