# Generated by Django 5.2.8 on 2026-01-04 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_saas', '0002_alter_platformsettings_instagram_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platformsettings',
            options={'verbose_name': 'Configuración del Sistema', 'verbose_name_plural': 'Configuración del Sistema'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='footer_text',
            field=models.CharField(blank=True, default='Todos los derechos reservados', max_length=200),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='site_name',
            field=models.CharField(default='Paso Ecosystem', max_length=100),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='instagram_link',
            field=models.CharField(blank=True, help_text='URL completa de Instagram', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Ej: 573001234567', max_length=20, null=True),
        ),
    ]
