# Generated by Django 5.2.8 on 2026-01-05 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('PENDING', '🟡 Pendiente de Abono (60 min)'), ('VERIFIED', '🟢 Verificada (Abono Recibido)'), ('COMPLETED', '🏁 Completada'), ('CANCELLED', '🔴 Cancelada'), ('EXPIRED', '⏱️ Expirada (No pagó)')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deposit_amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Monto Abono')),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Precio Total')),
                ('notes', models.TextField(blank=True, verbose_name='Notas del Cliente')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.businessprofile')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_appointments', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_appointments', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.service')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('start_time', models.TimeField(verbose_name='Entrada')),
                ('end_time', models.TimeField(verbose_name='Salida')),
                ('break_start', models.TimeField(blank=True, null=True, verbose_name='Inicio Almuerzo')),
                ('break_end', models.TimeField(blank=True, null=True, verbose_name='Fin Almuerzo')),
                ('is_active_day', models.BooleanField(default=True, help_text='Desactivar si el empleado faltó hoy', verbose_name='Trabaja hoy')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.businessprofile')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('employee', 'day_of_week')},
            },
        ),
    ]
