# Generated by Django 5.2.8 on 2026-01-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeschedule',
            name='is_active_day',
            field=models.BooleanField(default=True, verbose_name='Trabaja hoy'),
        ),
    ]
